services:
  - type: web
    name: delivery-receipt-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server_python.py
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_PW
        value: admin1234
      - key: DATABASE_URL
        sync: false
